# Cleaning data and generating chart for lateness

In [17]:
%pip install pyjanitor
%pip install --upgrade pandas

Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: pyjanitor in c:\users\sonya\appdata\local\programs\python\python311\lib\site-packages (0.32.20)
Requirement already satisfied: natsort<9,>=8.4.0 in c:\users\sonya\appdata\local\programs\python\python311\lib\site-packages (from pyjanitor) (8.4.0)
Requirement already satisfied: pandas-flavor<0.9,>=0.8.1 in c:\users\sonya\appdata\local\programs\python\python311\lib\site-packages (from pyjanitor) (0.8.1)
Requirement already satisfied: multipledispatch in c:\users\sonya\appdata\local\programs\python\python311\lib\site-packages (from pyjanitor) (1.0.0)
Requirement already satisfied: scipy in c:\users\sonya\appdata\local\programs\python\python311\lib\site-packages (from pyjanitor) (1.15.1)
Requirement already satisfied: janitor-rs<0.7,>=0.6.1 in c:\users\sonya\appdata\local\programs\python\python311\lib\site-packages (from pyjanitor) (0.6.1)
Requirement already satisfied: pandas>=0.23 in c:\users\sonya\appdata\local\programs\python\python311\lib\site-packages (from pandas-flavor<0.9,>=0.8.1->pyjanitor) (2.2.3)
Requirement already satisfied: xarray in c:\users\sonya\appdata\local\programs\python\python311\lib\site-packages (from pandas-flavor<0.9,>=0.8.1->pyjanitor) (2026.2.0)
Requirement already satisfied: numpy<2.5,>=1.23.5 in c:\users\sonya\appdata\local\programs\python\python311\lib\site-packages (from scipy->pyjanitor) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sonya\appdata\local\programs\python\python311\lib\site-packages (from pandas>=0.23->pandas-flavor<0.9,>=0.8.1->pyjanitor) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\sonya\appdata\local\programs\python\python311\lib\site-packages (from pandas>=0.23->pandas-flavor<0.9,>=0.8.1->pyjanitor) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\sonya\appdata\local\programs\python\python311\lib\site-packages (from pandas>=0.23->pandas-flavor<0.9,>=0.8.1->pyjanitor) (2024.2)
Requirement already satisfied: packaging>=24.1 in c:\users\sonya\appdata\local\programs\python\python311\lib\site-packages (from xarray->pandas-flavor<0.9,>=0.8.1->pyjanitor) (24.2)
Requirement already satisfied: six>=1.5 in c:\users\sonya\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.2->pandas>=0.23->pandas-flavor<0.9,>=0.8.1->pyjanitor) (1.17.0)

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pandas in c:\users\sonya\appdata\local\programs\python\python311\lib\site-packages (2.2.3)
Collecting pandas
  Downloading pandas-3.0.1-cp311-cp311-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\sonya\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sonya\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\sonya\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\sonya\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.1-cp311-cp311-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------- ----------------------- 4.2/9.9 MB 25.2 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 26.8 MB/s eta 0:00:00
Installing collected packages: pandas
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.3
    Uninstalling pandas-2.2.3:
      Successfully uninstalled pandas-2.2.3
Successfully installed pandas-3.0.1
Note: you may need to restart the kernel to use updated packages.

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\sonya\AppData\Local\Programs\Python\Python311\Lib\site-packages\~andas.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\sonya\AppData\Local\Programs\Python\Python311\Lib\site-packages\~andas'.
  You can safely remove it manually.

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [56]:
# Imports
import os
import pandas as pd
import numpy as np
from janitor import clean_names
import calendar
import datetime

In [48]:
overall_df = pd.DataFrame()

In [49]:
for idx in range(1, 13):
  days = calendar.monthrange(2023, idx)[1]
  for i in range(1, days + 1):
   name = calendar.month_name[idx]
   file_path = "./data/" + name + "/results_for_2023-" + "{:02n}".format(idx) + "-" + "{:02n}".format(i) +".csv"
   print(file_path)
   df = clean_names(pd.read_csv(file_path))
   df = df[['operation_date','service_rte_num','patt_direction','stop_id',
    'first_act_dep_time', 'first_act_arr_time', 'last_act_arr_time', 'last_act_dep_time', 'sched_arr_time', 'sched_dep_time', 'psngr_load']]
   df = df[df['sched_arr_time'] > 0]
   overall_df = pd.concat([overall_df, df])

./data/January/results_for_2023-01-01.csv
./data/January/results_for_2023-01-02.csv
./data/January/results_for_2023-01-03.csv
./data/January/results_for_2023-01-04.csv
./data/January/results_for_2023-01-05.csv
./data/January/results_for_2023-01-06.csv
./data/January/results_for_2023-01-07.csv
./data/January/results_for_2023-01-08.csv
./data/January/results_for_2023-01-09.csv
./data/January/results_for_2023-01-10.csv
./data/January/results_for_2023-01-11.csv
./data/January/results_for_2023-01-12.csv
./data/January/results_for_2023-01-13.csv
./data/January/results_for_2023-01-14.csv
./data/January/results_for_2023-01-15.csv
./data/January/results_for_2023-01-16.csv
./data/January/results_for_2023-01-17.csv
./data/January/results_for_2023-01-18.csv
./data/January/results_for_2023-01-19.csv
./data/January/results_for_2023-01-20.csv
./data/January/results_for_2023-01-21.csv
./data/January/results_for_2023-01-22.csv
./data/January/results_for_2023-01-23.csv
./data/January/results_for_2023-01-24.csv
./data/January/results_for_2023-01-25.csv
./data/January/results_for_2023-01-26.csv
./data/January/results_for_2023-01-27.csv
./data/January/results_for_2023-01-28.csv
./data/January/results_for_2023-01-29.csv
./data/January/results_for_2023-01-30.csv
./data/January/results_for_2023-01-31.csv
./data/February/results_for_2023-02-01.csv
./data/February/results_for_2023-02-02.csv
./data/February/results_for_2023-02-03.csv
./data/February/results_for_2023-02-04.csv
./data/February/results_for_2023-02-05.csv
./data/February/results_for_2023-02-06.csv
./data/February/results_for_2023-02-07.csv
./data/February/results_for_2023-02-08.csv
./data/February/results_for_2023-02-09.csv
./data/February/results_for_2023-02-10.csv
./data/February/results_for_2023-02-11.csv
./data/February/results_for_2023-02-12.csv
./data/February/results_for_2023-02-13.csv
./data/February/results_for_2023-02-14.csv
./data/February/results_for_2023-02-15.csv
./data/February/results_for_2023-02-16.csv
./data/February/results_for_2023-02-17.csv
./data/February/results_for_2023-02-18.csv
./data/February/results_for_2023-02-19.csv
./data/February/results_for_2023-02-20.csv
./data/February/results_for_2023-02-21.csv
./data/February/results_for_2023-02-22.csv
./data/February/results_for_2023-02-23.csv
./data/February/results_for_2023-02-24.csv
./data/February/results_for_2023-02-25.csv
./data/February/results_for_2023-02-26.csv
./data/February/results_for_2023-02-27.csv
./data/February/results_for_2023-02-28.csv
./data/March/results_for_2023-03-01.csv
./data/March/results_for_2023-03-02.csv
./data/March/results_for_2023-03-03.csv
./data/March/results_for_2023-03-04.csv
./data/March/results_for_2023-03-05.csv
./data/March/results_for_2023-03-06.csv
./data/March/results_for_2023-03-07.csv
./data/March/results_for_2023-03-08.csv
./data/March/results_for_2023-03-09.csv
./data/March/results_for_2023-03-10.csv
./data/March/results_for_2023-03-11.csv
./data/March/results_for_2023-03-12.csv
./data/March/results_for_2023-03-13.csv
./data/March/results_for_2023-03-14.csv
./data/March/results_for_2023-03-15.csv
./data/March/results_for_2023-03-16.csv
./data/March/results_for_2023-03-17.csv
./data/March/results_for_2023-03-18.csv
./data/March/results_for_2023-03-19.csv
./data/March/results_for_2023-03-20.csv
./data/March/results_for_2023-03-21.csv
./data/March/results_for_2023-03-22.csv
./data/March/results_for_2023-03-23.csv
./data/March/results_for_2023-03-24.csv
./data/March/results_for_2023-03-25.csv
./data/March/results_for_2023-03-26.csv
./data/March/results_for_2023-03-27.csv
./data/March/results_for_2023-03-28.csv
./data/March/results_for_2023-03-29.csv
./data/March/results_for_2023-03-30.csv
./data/March/results_for_2023-03-31.csv
./data/April/results_for_2023-04-01.csv
./data/April/results_for_2023-04-02.csv
./data/April/results_for_2023-04-03.csv
./data/April/results_for_2023-04-04.csv
./data/April/results_for_2023-04-05.csv
./data/April/results_for_2023-04-06.csv
./data/April/results_for_2023-04-07.csv
./data/April/results_for_2023-04-08.csv
./data/April/results_for_2023-04-09.csv
./data/April/results_for_2023-04-10.csv
./data/April/results_for_2023-04-11.csv
./data/April/results_for_2023-04-12.csv
./data/April/results_for_2023-04-13.csv
./data/April/results_for_2023-04-14.csv
./data/April/results_for_2023-04-15.csv
./data/April/results_for_2023-04-16.csv
./data/April/results_for_2023-04-17.csv
./data/April/results_for_2023-04-18.csv
./data/April/results_for_2023-04-19.csv
./data/April/results_for_2023-04-20.csv
./data/April/results_for_2023-04-21.csv
./data/April/results_for_2023-04-22.csv
./data/April/results_for_2023-04-23.csv
./data/April/results_for_2023-04-24.csv
./data/April/results_for_2023-04-25.csv
./data/April/results_for_2023-04-26.csv
./data/April/results_for_2023-04-27.csv
./data/April/results_for_2023-04-28.csv
./data/April/results_for_2023-04-29.csv
./data/April/results_for_2023-04-30.csv
./data/May/results_for_2023-05-01.csv
./data/May/results_for_2023-05-02.csv
./data/May/results_for_2023-05-03.csv
./data/May/results_for_2023-05-04.csv
./data/May/results_for_2023-05-05.csv
./data/May/results_for_2023-05-06.csv
./data/May/results_for_2023-05-07.csv
./data/May/results_for_2023-05-08.csv
./data/May/results_for_2023-05-09.csv
./data/May/results_for_2023-05-10.csv
./data/May/results_for_2023-05-11.csv
./data/May/results_for_2023-05-12.csv
./data/May/results_for_2023-05-13.csv
./data/May/results_for_2023-05-14.csv
./data/May/results_for_2023-05-15.csv
./data/May/results_for_2023-05-16.csv
./data/May/results_for_2023-05-17.csv
./data/May/results_for_2023-05-18.csv
./data/May/results_for_2023-05-19.csv
./data/May/results_for_2023-05-20.csv
./data/May/results_for_2023-05-21.csv
./data/May/results_for_2023-05-22.csv
./data/May/results_for_2023-05-23.csv
./data/May/results_for_2023-05-24.csv
./data/May/results_for_2023-05-25.csv
./data/May/results_for_2023-05-26.csv
./data/May/results_for_2023-05-27.csv
./data/May/results_for_2023-05-28.csv
./data/May/results_for_2023-05-29.csv
./data/May/results_for_2023-05-30.csv
./data/May/results_for_2023-05-31.csv
./data/June/results_for_2023-06-01.csv
./data/June/results_for_2023-06-02.csv
./data/June/results_for_2023-06-03.csv
./data/June/results_for_2023-06-04.csv
./data/June/results_for_2023-06-05.csv
./data/June/results_for_2023-06-06.csv
./data/June/results_for_2023-06-07.csv
./data/June/results_for_2023-06-08.csv
./data/June/results_for_2023-06-09.csv
./data/June/results_for_2023-06-10.csv
./data/June/results_for_2023-06-11.csv
./data/June/results_for_2023-06-12.csv
./data/June/results_for_2023-06-13.csv
./data/June/results_for_2023-06-14.csv
./data/June/results_for_2023-06-15.csv
./data/June/results_for_2023-06-16.csv
./data/June/results_for_2023-06-17.csv
./data/June/results_for_2023-06-18.csv
./data/June/results_for_2023-06-19.csv
./data/June/results_for_2023-06-20.csv
./data/June/results_for_2023-06-21.csv
./data/June/results_for_2023-06-22.csv
./data/June/results_for_2023-06-23.csv
./data/June/results_for_2023-06-24.csv
./data/June/results_for_2023-06-25.csv
./data/June/results_for_2023-06-26.csv
./data/June/results_for_2023-06-27.csv
./data/June/results_for_2023-06-28.csv
./data/June/results_for_2023-06-29.csv
./data/June/results_for_2023-06-30.csv
./data/July/results_for_2023-07-01.csv
./data/July/results_for_2023-07-02.csv
./data/July/results_for_2023-07-03.csv
./data/July/results_for_2023-07-04.csv
./data/July/results_for_2023-07-05.csv
./data/July/results_for_2023-07-06.csv
./data/July/results_for_2023-07-07.csv
./data/July/results_for_2023-07-08.csv
./data/July/results_for_2023-07-09.csv
./data/July/results_for_2023-07-10.csv
./data/July/results_for_2023-07-11.csv
./data/July/results_for_2023-07-12.csv
./data/July/results_for_2023-07-13.csv
./data/July/results_for_2023-07-14.csv
./data/July/results_for_2023-07-15.csv
./data/July/results_for_2023-07-16.csv
./data/July/results_for_2023-07-17.csv
./data/July/results_for_2023-07-18.csv
./data/July/results_for_2023-07-19.csv
./data/July/results_for_2023-07-20.csv
./data/July/results_for_2023-07-21.csv
./data/July/results_for_2023-07-22.csv
./data/July/results_for_2023-07-23.csv
./data/July/results_for_2023-07-24.csv
./data/July/results_for_2023-07-25.csv
./data/July/results_for_2023-07-26.csv
./data/July/results_for_2023-07-27.csv
./data/July/results_for_2023-07-28.csv
./data/July/results_for_2023-07-29.csv
./data/July/results_for_2023-07-30.csv
./data/July/results_for_2023-07-31.csv
./data/August/results_for_2023-08-01.csv
./data/August/results_for_2023-08-02.csv
./data/August/results_for_2023-08-03.csv
./data/August/results_for_2023-08-04.csv
./data/August/results_for_2023-08-05.csv
./data/August/results_for_2023-08-06.csv
./data/August/results_for_2023-08-07.csv
./data/August/results_for_2023-08-08.csv
./data/August/results_for_2023-08-09.csv
./data/August/results_for_2023-08-10.csv
./data/August/results_for_2023-08-11.csv
./data/August/results_for_2023-08-12.csv
./data/August/results_for_2023-08-13.csv
./data/August/results_for_2023-08-14.csv
./data/August/results_for_2023-08-15.csv
./data/August/results_for_2023-08-16.csv
./data/August/results_for_2023-08-17.csv
./data/August/results_for_2023-08-18.csv
./data/August/results_for_2023-08-19.csv
./data/August/results_for_2023-08-20.csv
./data/August/results_for_2023-08-21.csv
./data/August/results_for_2023-08-22.csv
./data/August/results_for_2023-08-23.csv
./data/August/results_for_2023-08-24.csv
./data/August/results_for_2023-08-25.csv
./data/August/results_for_2023-08-26.csv
./data/August/results_for_2023-08-27.csv
./data/August/results_for_2023-08-28.csv
./data/August/results_for_2023-08-29.csv
./data/August/results_for_2023-08-30.csv
./data/August/results_for_2023-08-31.csv
./data/September/results_for_2023-09-01.csv
./data/September/results_for_2023-09-02.csv
./data/September/results_for_2023-09-03.csv
./data/September/results_for_2023-09-04.csv
./data/September/results_for_2023-09-05.csv
./data/September/results_for_2023-09-06.csv
./data/September/results_for_2023-09-07.csv
./data/September/results_for_2023-09-08.csv
./data/September/results_for_2023-09-09.csv
./data/September/results_for_2023-09-10.csv
./data/September/results_for_2023-09-11.csv
./data/September/results_for_2023-09-12.csv
./data/September/results_for_2023-09-13.csv
./data/September/results_for_2023-09-14.csv
./data/September/results_for_2023-09-15.csv
./data/September/results_for_2023-09-16.csv
./data/September/results_for_2023-09-17.csv
./data/September/results_for_2023-09-18.csv
./data/September/results_for_2023-09-19.csv
./data/September/results_for_2023-09-20.csv
./data/September/results_for_2023-09-21.csv
./data/September/results_for_2023-09-22.csv
./data/September/results_for_2023-09-23.csv
./data/September/results_for_2023-09-24.csv
./data/September/results_for_2023-09-25.csv
./data/September/results_for_2023-09-26.csv
./data/September/results_for_2023-09-27.csv
./data/September/results_for_2023-09-28.csv
./data/September/results_for_2023-09-29.csv
./data/September/results_for_2023-09-30.csv
./data/October/results_for_2023-10-01.csv
./data/October/results_for_2023-10-02.csv
./data/October/results_for_2023-10-03.csv
./data/October/results_for_2023-10-04.csv
./data/October/results_for_2023-10-05.csv
./data/October/results_for_2023-10-06.csv
./data/October/results_for_2023-10-07.csv
./data/October/results_for_2023-10-08.csv
./data/October/results_for_2023-10-09.csv
./data/October/results_for_2023-10-10.csv
./data/October/results_for_2023-10-11.csv
./data/October/results_for_2023-10-12.csv
./data/October/results_for_2023-10-13.csv
./data/October/results_for_2023-10-14.csv
./data/October/results_for_2023-10-15.csv
./data/October/results_for_2023-10-16.csv
./data/October/results_for_2023-10-17.csv
./data/October/results_for_2023-10-18.csv
./data/October/results_for_2023-10-19.csv
./data/October/results_for_2023-10-20.csv
./data/October/results_for_2023-10-21.csv
./data/October/results_for_2023-10-22.csv
./data/October/results_for_2023-10-23.csv
./data/October/results_for_2023-10-24.csv
./data/October/results_for_2023-10-25.csv
./data/October/results_for_2023-10-26.csv
./data/October/results_for_2023-10-27.csv
./data/October/results_for_2023-10-28.csv
./data/October/results_for_2023-10-29.csv
./data/October/results_for_2023-10-30.csv
./data/October/results_for_2023-10-31.csv
./data/November/results_for_2023-11-01.csv
./data/November/results_for_2023-11-02.csv
./data/November/results_for_2023-11-03.csv
./data/November/results_for_2023-11-04.csv
./data/November/results_for_2023-11-05.csv
./data/November/results_for_2023-11-06.csv
./data/November/results_for_2023-11-07.csv
./data/November/results_for_2023-11-08.csv
./data/November/results_for_2023-11-09.csv
./data/November/results_for_2023-11-10.csv
./data/November/results_for_2023-11-11.csv
./data/November/results_for_2023-11-12.csv
./data/November/results_for_2023-11-13.csv
./data/November/results_for_2023-11-14.csv
./data/November/results_for_2023-11-15.csv
./data/November/results_for_2023-11-16.csv
./data/November/results_for_2023-11-17.csv
./data/November/results_for_2023-11-18.csv
./data/November/results_for_2023-11-19.csv
./data/November/results_for_2023-11-20.csv
./data/November/results_for_2023-11-21.csv
./data/November/results_for_2023-11-22.csv
./data/November/results_for_2023-11-23.csv
./data/November/results_for_2023-11-24.csv
./data/November/results_for_2023-11-25.csv
./data/November/results_for_2023-11-26.csv
./data/November/results_for_2023-11-27.csv
./data/November/results_for_2023-11-28.csv
./data/November/results_for_2023-11-29.csv
./data/November/results_for_2023-11-30.csv
./data/December/results_for_2023-12-01.csv
./data/December/results_for_2023-12-02.csv
./data/December/results_for_2023-12-03.csv
./data/December/results_for_2023-12-04.csv
./data/December/results_for_2023-12-05.csv
./data/December/results_for_2023-12-06.csv
./data/December/results_for_2023-12-07.csv
./data/December/results_for_2023-12-08.csv
./data/December/results_for_2023-12-09.csv
./data/December/results_for_2023-12-10.csv
./data/December/results_for_2023-12-11.csv
./data/December/results_for_2023-12-12.csv
./data/December/results_for_2023-12-13.csv
./data/December/results_for_2023-12-14.csv
./data/December/results_for_2023-12-15.csv
./data/December/results_for_2023-12-16.csv
./data/December/results_for_2023-12-17.csv
./data/December/results_for_2023-12-18.csv
./data/December/results_for_2023-12-19.csv
./data/December/results_for_2023-12-20.csv
./data/December/results_for_2023-12-21.csv
./data/December/results_for_2023-12-22.csv
./data/December/results_for_2023-12-23.csv
./data/December/results_for_2023-12-24.csv
./data/December/results_for_2023-12-25.csv
./data/December/results_for_2023-12-26.csv
./data/December/results_for_2023-12-27.csv
./data/December/results_for_2023-12-28.csv
./data/December/results_for_2023-12-29.csv
./data/December/results_for_2023-12-30.csv
./data/December/results_for_2023-12-31.csv

In [50]:
print(overall_df.shape)
overall_df.head(-5)

(24325636, 11)

,operation_date,service_rte_num,patt_direction,stop_id,first_act_dep_time,first_act_arr_time,last_act_arr_time,last_act_dep_time,sched_arr_time,sched_dep_time,psngr_load
0,2023-01-01,545,E,21765,23367.0,23367.0,23367.0,23367.0,22740,22740,0
1,2023-01-01,545,E,620,23650.0,23650.0,23650.0,23650.0,22920,22740,0
2,2023-01-01,545,E,700,23811.0,23770.0,23770.0,23811.0,23160,22740,1
3,2023-01-01,545,E,71348,24334.0,24334.0,24334.0,24334.0,23880,22740,1
4,2023-01-01,545,E,71336,24715.0,24715.0,24715.0,24715.0,24300,22740,1
...,...,...,...,...,...,...,...,...,...,...,...
48514,2023-12-31,14,N,11690,20917.0,20917.0,20917.0,20917.0,20820,20820,0
48515,2023-12-31,14,N,8403,21071.0,21056.0,21056.0,21071.0,21000,20820,1
48516,2023-12-31,14,N,11910,21496.0,21496.0,21496.0,21496.0,21480,20820,1
48517,2023-12-31,14,N,3600,21721.0,21721.0,21721.0,21721.0,21720,20820,2
48518,2023-12-31,1,N,3600,21735.0,21735.0,21735.0,21735.0,21720,21720,4

In [51]:
overall_df.to_csv("All365Days.csv")

In [ ]:
# overall_df = pd.read_csv("All365Days.csv")

In [54]:
# Calulcate lateness for all columns
overall_df['lateness'] = overall_df['first_act_arr_time'] - overall_df['sched_arr_time']
overall_df = overall_df[overall_df['lateness'] > -3600]
overall_df = overall_df[overall_df['lateness'] < 5400]

In [60]:
# Add days of week column
day_names = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
overall_df['weekday'] = [datetime.datetime.strptime(overall_df['operation_date'].iloc[i], '%Y-%m-%d').strftime('%A') for i in range(len(overall_df))]

In [ ]:
# overall_df.to_csv('AllDaysWithDateandLate.csv')

KeyboardInterrupt:

In [129]:
overall_df = pd.read_csv('AllDaysWithDateandLate.csv')

In [130]:
overall_df.head()

,Unnamed: 0.1,Unnamed: 0,operation_date,service_rte_num,patt_direction,stop_id,first_act_dep_time,first_act_arr_time,last_act_arr_time,last_act_dep_time,sched_arr_time,sched_dep_time,psngr_load,lateness,weekday
0,0,0,2023-01-01,545,E,21765,23367.0,23367.0,23367.0,23367.0,22740,22740,0,627.0,Sunday
1,1,1,2023-01-01,545,E,620,23650.0,23650.0,23650.0,23650.0,22920,22740,0,730.0,Sunday
2,2,2,2023-01-01,545,E,700,23811.0,23770.0,23770.0,23811.0,23160,22740,1,610.0,Sunday
3,3,3,2023-01-01,545,E,71348,24334.0,24334.0,24334.0,24334.0,23880,22740,1,454.0,Sunday
4,4,4,2023-01-01,545,E,71336,24715.0,24715.0,24715.0,24715.0,24300,22740,1,415.0,Sunday

In [131]:
average = overall_df.groupby(['service_rte_num', 'patt_direction', 'stop_id', 'sched_arr_time', 'weekday'])[['lateness', 'psngr_load']].mean().reset_index()

In [ ]:
# average.to_csv('AverageDays.csv')

In [152]:
average = pd.read_csv('AverageDays.csv')

In [154]:
average['sched_arr_time_formatted'] = pd.to_datetime(average['sched_arr_time'], unit='s').dt.strftime('%H:%M:%S')

In [155]:
average['lateness minutes'] = pd.to_datetime(average['lateness'], unit='s').dt.strftime('%M:%S')

In [156]:
average = average.drop('Unnamed: 0', axis=1)

In [ ]:
#average.to_csv('AverageDaysFormatted.csv')

In [214]:
average = pd.read_csv('AverageDaysFormatted.csv')
average = average.drop('Unnamed: 0', axis=1)

In [163]:
average.head()

,service_rte_num,patt_direction,stop_id,sched_arr_time,weekday,lateness,psngr_load,sched_arr_time_formatted,lateness minutes
0,1,N,575,18540,Friday,255.500000,8.00,05:09:00,04:15
1,1,N,575,18540,Monday,189.333333,9.00,05:09:00,03:09
2,1,N,575,18540,Thursday,30.250000,5.25,05:09:00,00:30
3,1,N,575,18540,Tuesday,64.250000,8.00,05:09:00,01:04
4,1,N,575,18540,Wednesday,79.000000,6.50,05:09:00,01:19

In [215]:
average['sched_arr_time_formatted'] = pd.to_datetime(average['sched_arr_time'], unit='s')

In [216]:
times = average.groupby([pd.Grouper(key='sched_arr_time_formatted', freq='5min'), pd.Grouper('stop_id'), pd.Grouper('weekday')])[['lateness', 'psngr_load']].mean().reset_index()

In [192]:
average[(average['weekday'] == "Friday") & (average['stop_id'] == 1530) & (average['sched_arr_time_formatted'] < '1970-01-01 03:55:00') & (average['sched_arr_time_formatted'] >= '1970-01-01 03:45:00')]

,service_rte_num,patt_direction,stop_id,sched_arr_time,weekday,lateness,psngr_load,sched_arr_time_formatted,lateness minutes
12944,3,N,1530,14040,Friday,277.75,0.5,1970-01-01 03:54:00,04:37

In [217]:
times['sched_arr_time_formatted'] = pd.to_datetime(times['sched_arr_time_formatted']).dt.strftime('%H:%M:%S')

In [218]:
times['lateness minutes'] = pd.to_datetime(times['lateness'], unit='s').dt.strftime('%M:%S')

In [219]:
times['service_rte_num'] = 0

In [210]:
route_times = average.groupby([pd.Grouper(key='sched_arr_time_formatted', freq='5min'), pd.Grouper('stop_id'), pd.Grouper('weekday'), pd.Grouper('service_rte_num')])[['lateness', 'psngr_load']].mean().reset_index()

In [220]:
route_times['sched_arr_time_formatted'] = pd.to_datetime(route_times['sched_arr_time_formatted']).dt.strftime('%H:%M:%S')
route_times['lateness minutes'] = pd.to_datetime(route_times['lateness'], unit='s').dt.strftime('%M:%S')

In [221]:
times.head()

,sched_arr_time_formatted,stop_id,weekday,lateness,psngr_load,lateness minutes,service_rte_num
0,03:50:00,1530,Friday,277.75,0.5,04:37,0
1,03:50:00,1530,Monday,32.00,0.0,00:32,0
2,03:50:00,1530,Tuesday,858.00,0.0,14:18,0
3,03:55:00,1530,Monday,60.00,0.0,01:00,0
4,03:55:00,1530,Saturday,347.00,0.0,05:47,0

In [223]:
avg_times = pd.concat([times, route_times])

In [226]:
avg_times.to_csv('FiveMinuteDelayAverages.csv')